server:
  port: 8083
spring:
  application:
    name: search-service
  datasource:
    url: jdbc:mysql://localhost:3306/heima
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.10.222:9200
  jackson:
    default-property-inclusion: non_null # 配置json处理时忽略空值
eureka:
  client:
    service-url:
      defaltZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10 #每10秒拉去一次微服务
  instance:
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳