server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oa?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.chai.service.pojo